import type { Metadata } from "next";
import AuthProvider from "@/components/AuthProvider";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import { Providers } from "@/redux/Providers";
import Footer from "@/components/nav/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Healthx360: take back control of your health",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${poppins.className} bg-antiflash`}>
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </body>
      </AuthProvider>
    </html>
  );
}
